DROP TABLE IF EXISTS LLAVES_SPI;

CREATE TABLE LLAVES_SPI (
  TIPO_LLAVE              VARCHAR(1)  NOT NULL,
  NUMERO_LLAVE            VARCHAR(20) NOT NULL,
  TIPO_IDENTIFICACION     VARCHAR(4)  NOT NULL,
  NUMERO_IDENTIFICACION   VARCHAR(18) NOT NULL,
  TIPO_DE_PERSONA         VARCHAR(2)  NOT NULL,
  NOMBRE_PERSONA_JURIDICA VARCHAR(140),
  PRIMER_NOMBRE_PN        VARCHAR(40),
  SEGUNDO_NOMBRE_PN       VARCHAR(40),
  PRIMER_APELLIDO_PN      VARCHAR(40),
  SEGUNDO_APELLIDO_PN     VARCHAR(40),
  NIT_ENTIDAD_EMISORA     NUMERIC(9)  NOT NULL,
  TIPO_MEDIO_DE_PAGO      VARCHAR(4)  NOT NULL,
  NUMERO_MEDIO_DE_PAGO    NUMERIC(34) NOT NULL,
  FECHA_CREACION          VARCHAR(23) NOT NULL,
  FECHA_MODIFICACION      VARCHAR(23),
  ESTADO_DE_LLAVE         VARCHAR(10) NOT NULL,
  CODIGO_BANCO_AVAL       NUMERIC(4)  NOT NULL,
  LLAVE_FAVORITA          VARCHAR(1)  NOT NULL,
  ACCION                  VARCHAR(1)  NOT NULL,
  NOMBRE_DE_ARCHIVO       VARCHAR(80),
  NUMERO_LINEA_DE_REGISTRO NUMERIC(6),
  ESTADO_LLAVE_BANCO      VARCHAR(400),
  PRIMARY KEY (NUMERO_LLAVE)
);

