DROP TABLE IF EXISTS LLAVES_SPI;

CREATE TABLE LLAVES_SPI(
TIPO_LLAVE VARCHAR2(1) ,
NUMERO_LLAVE VARCHAR2(20) ,
TIPO_IDENTIFICACION VARCHAR2(4) ,
NUMERO_IDENTIFICACION VARCHAR2(18)  ,
TIPO_DE_PERSONA VARCHAR2(2)  ,
NOMBRE_PERSONA_JURIDICA VARCHAR2(140),
PRIMER_NOMBRE_PN VARCHAR2(40),
SEGUNDO_NOMBRE_PN VARCHAR2(40),
PRIMER_APELLIDO_PN VARCHAR2(40),
SEGUNDO_APELLIDO_PN VARCHAR2(40),
NIT_ENTIDAD_EMISORA NUMBER(9) ,
TIPO_MEDIO_DE_PAGO VARCHAR2(4)   ,
NUMERO_MEDIO_DE_PAGO NUMBER(34)  ,
FECHA_CREACION VARCHAR2(23)  ,
FECHA_MODIFICACION VARCHAR2(23),
ESTADO_DE_LLAVE VARCHAR2(10)  ,
CODIGO_BANCO_AVAL NUMBER(4),
LLAVE_FAVORITA VARCHAR2(1)  ,
ACCION VARCHAR2(1) ,
NOMBRE_DE_ARCHIVO VARCHAR2(80),
NUMERO_LINEA_DE_REGISTRO NUMBER(6),
ESTADO_LLAVE_BANCO VARCHAR2(400)
);